from setuptools import setup

setup(
    name='pubmed-author-affiliation',
    version='0.2',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.pip',
              'venv.lib.python2.7.site-packages.pip._vendor', 'venv.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip._internal.operations', 'venv.lib.python2.7.site-packages.lxml',
              'venv.lib.python2.7.site-packages.lxml.html', 'venv.lib.python2.7.site-packages.lxml.includes',
              'venv.lib.python2.7.site-packages.lxml.isoschematron', 'venv.lib.python2.7.site-packages.zope.interface',
              'venv.lib.python2.7.site-packages.zope.interface.tests',
              'venv.lib.python2.7.site-packages.zope.interface.common',
              'venv.lib.python2.7.site-packages.zope.interface.common.tests', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.tool', 'venv.lib.python2.7.site-packages.wheel.signatures',
              'venv.lib.python2.7.site-packages.markupsafe', 'venv.lib.python2.7.site-packages.setuptools',
              'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools._vendor',
              'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pkg_resources',
              'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip-10.0.1-py2.7.egg.pip._internal.operations',
              'pubmedAuthorAffiliation'],
    url='',
    license='Apache 2',
    author='Ardan Patwardhan',
    author_email='ardan@ebi.ac.uk',
    description='Search for author affiliations from Pubmed for a list of Pubmed IDs and DOIs'
)
